<?php
$images = $block->getImages();
$is_active = 1;
$id = 'alphatech_homepage_slider';
$interval = 3000;
?>
<div id="<?php echo $id;?>" class="carousel slide" data-ride="carousel" data-interval="<?php echo $interval?>">
  <div class="carousel-inner">
  	<?php foreach($images as $image) { ?>
  	<div class="carousel-item <?php echo $is_active ? 'active':''?>">
      <a href="<?php echo $image['link']?>" title="<?php echo $image['title']?>">
        <img class="d-block w-100" src="<?php echo $image['image_url']?>" alt="<?php echo $image['title']?>" />
      </a>
    </div>
    <?php $is_active = 0 ?>
  	<?php } ?>
  </div>
  <a class="carousel-control-prev" href="#<?php echo $id;?>" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"><i class="fas fa-angle-left"></i></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#<?php echo $id;?>" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"><i class="fas fa-angle-right"></i></span>
    <span class="sr-only">Next</span>
  </a>
</div>
